version: '3.5'

services:
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  s3:
    image: s1s5/pgbackup
    build:
      context: .
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/postgres
      - S3_BUCKET_NAME=$S3_BUCKET_NAME
      - S3_PATH=$S3_PATH
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    command: /bin/bash -c "sleep 60; /bin/bash ./run_backup.sh"

  dropbox:
    image: s1s5/pgbackup:dropbox
    build:
      context: dropbox
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/postgres
      - DROPBOX_TOKEN=$DROPBOX_TOKEN
      - DROPBOX_PATH=$DROPBOX_PATH
    command: /bin/bash -c "sleep 60; /bin/bash ./run_backup.sh"
